In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('asd.csv')
df

                                                                                                                                                                                                                                                                                                                                                                                                                        Formue efter population, alder, enhed, tid, omraade og formuetype
                                                                                                           Nettoformue I alt (2020-definition A+B+CX-D-E-F) Aktiver I alt (2020-definition A+B+CX) A.1. Helaarsbolig, Ejerboliger A.5. Biler B. Finansiel formue i alt (2020-defintion) B.1. Indestaaende i pengeinstitutter B.2. Obligationer B.3. Aktier i depot (oftest noterede) mv. B.4. Andel i investeringsfonde         B.7. indestaaende paa virksomhedsordningen
Alle uanset om de har formuetypen NaN               NaN                            NaN  NaN                NaN                                              NaN                                    NaN                            NaN        NaN                                        NaN                                  NaN               NaN                                       NaN                                                                           NaN
                                  18 aar og derover NaN                            NaN  NaN                NaN                                              NaN                                    NaN                            NaN        NaN                                        NaN                                  NaN               NaN                                       NaN                                                                           NaN
                                                    Gennemsnit (faste priser 2021) NaN  NaN                NaN                                              NaN                                    NaN                            NaN        NaN                                        NaN                                  NaN               NaN                                       NaN                                                                           NaN
                                                                                   2022 NaN                NaN                                              NaN                                    NaN                            NaN        NaN                                        NaN                                  NaN               NaN                                       NaN                                                                           NaN
                                                                                        Hele landet        1728148                                          2231330                                657746                         39360      718362                                     176259                               4373              80796                                     75665                                                                       33629
                                                                                        Region Hovedstaden 2045446                                          2599282                                743916                         32182      917403                                     202947                               7847              145475                                    102599                                                                      32570
                                                                                        Koobenhavn         1381562                                          1799293                                374635                         17170      624541                                     169265                               4253              78716                                     67041                                                                       18550
                                                                                        Frederiksberg      2414549                                          2960659                                604032                         23020      1141848                                    248269                               10521             153276                                    133566                                                                      38410
                                                                                        Dragoor            3047291                                          3973202                                1650031                        49339      1067276                                    267646                               6521              119972                                    134226                                                                      46843
                                                                                        Gentofte           6415320                                          7822314                                1978968                        46571      3913204                                    447709                               47195             726880                                    372008                                                                     194427
                                                                                        Lyngby-Taarbaek    3458146                                          4236362                                1216019                        39278      1795766                                    276593                               22277             445518                                    208898                                                                      51158
                                                                                        Allerood           2864295                                          3612175                                1397630                        52804      1010117                                    245301                               7236              170642                                    140549                                                                      31430
                                                                                        Fredensborg        2665565                                          3339521                                1079947                        46932      1221946                                    225138                               12816             243718                                    136790                                                                      49255
                                                                                        Furesoo            2835789                                          3574325                                1316730                        47860      1065586                                    243345                               7900              200837                                    153786                                                                      39623
                                                                                        Gribskov           2051861                                          2677911                                931630                         49731      777811                                     215158                               4720              100872                                    104579                                                                      31257
                                                                                        Helsingoor         2124936                                          2736708                                860619                         41609      934813                                     200230                               7858              155490                                    108969                                                                      35251
                                                                                        Hoorsholm          5244541                                          6403950                                1732209                        57792      3017089                                    368327                               30243             412272                                    255381                                                                     100388
                                                                                        Rudersdal          5815412                                          6973547                                1814120                        55087      3481693                                    368338                               34912             625257                                    290509                                                                     126470
                                                                                        Roskilde           2097101                                          2695556                                925985                         43538      794095                                     208000                               5039              109791                                    100335                                                                      27329
                                                                                        Solrood            2382112                                          3146439                                1252600                        52282      914939                                     210075                               3896              70810                                     94641                                                                       32191
                                                                                        Skanderborg        2062104                                          2735060                                1002650                        50480      773229                                     195240                               2243              50672                                     76983                                                                       42565